server:
  port: 8088
camelsimple:
  api:
    path: /camel
  route:
    path: /route/dev/pub
camel:
  springboot:
    name: CamelSimple
management:
  port: ${server.port}
  security:
    enabled: false
endpoints:
  enabled: true
  health:
    enabled: true
  jolokia:
    sensitive: false

quickstart:
  generateOrderPeriod: 10s
  processOrderPeriod: 30s
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:bootapp;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: null
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true            
in3in2route:
  from: file://C:/in3/?charset=utf-8
  toUri1: file://C:/in2A1/
  toUri2: file://C:/in2B/
in5ftproute:
  from: file://C:/in5/?charset=utf-8
  toUri1: ftp://dlpuser@dlptest.com@ftp.dlptest.com/upload?password=3D6XZV9MKdhM5fF&ftpClient.dataTimeout=30000
  
resources:
  extract:
    dir: /route/dev/  

kafka:
  producer:
    endpoint: kafka:localhost:9092?topic=test&brokers=localhost:9092      
  consumer:
    endpoint: kafka:localhost:9092?topic=test&groupId=testing&brokers=localhost:9092&autoOffsetReset=earliest&consumersCount=1          
    
hawtio:
  authenticationEnabled: false